Repository Leoy23/down-with-the-fitness, pull requests merged in 2022-09, with the labels that each got.

#44 Adds a better version of the find ID method
  src/Hydration.js
  src/scripts.js
  test/Hydration-test.js
Labels: bug, enhancement

#48 Adds the rest of hydration methods
  src/Hydration.js
  src/Sleep.js
  test/Hydration-test.js
  test/Sleep-test.js
Labels: enhancement

#51 Adds hydration data to Dom
  src/css/styles.css
  src/scripts.js
Labels: feature

#52 Adds more hydro dom data
  src/css/styles.css
  src/scripts.js
Labels: feature

#54 add displaySleepData
  src/Sleep.js
  src/scripts.js
Labels: enhancement, feature

#55 Fix small changes to ReadME and enhance HTML and CSS
  README.md
  dist/index.html
  src/css/styles.css
  src/scripts.js
Labels: enhancement, feature

#57 Update sleep dashboard
  src/Hydration.js
  src/Sleep.js
  src/scripts.js
  test/Sleep-test.js
Labels: bug, help wanted, invalid, question

#58 Finish sleep method bugs
  src/Sleep.js
  src/scripts.js
Labels: enhancement, feature

#59 Works on displaying user friend names
  src/scripts.js
Labels: bug, help wanted

#62 Fixes css file path issues
  src/css/styles.css
Labels: documentation

#63 Finish the findUserFriend function
  src/UserRepository.js
  src/css/styles.css
  src/scripts.js
Labels: enhancement

#64 Add styling to html & css
  dist/index.html
  src/css/styles.css
  src/images/brain.png
  src/images/constellation.png
  src/images/galaxy.png
  src/images/milky-way.png
  src/scripts.js
Labels: enhancement

#70 Adds feedback changes to the first widget
  dist/index.html
  src/css/styles.css
  src/scripts.js
Labels: enhancement, accessibility

#72 Add feedback changes, pull HTML out of scripts
  dist/index.html
  src/scripts.js
Labels: enhancement

#73 refactor displaySleepData
  dist/index.html
  src/scripts.js
Labels: documentation, feature

#74 Adds corrections from feedback for user steps comparison
  dist/index.html
  src/css/styles.css
  src/scripts.js
Labels: documentation, accessibility

#76 Feature activity
  src/Activity.js
  test/Activity-test.js
Labels: documentation, enhancement

#75 Adds corrections to html and styles to show full application on page
  dist/index.html
  src/css/styles.css
  src/scripts.js
Labels: documentation, accessibility

#77 Adds more styles
  dist/index.html
  src/css/styles.css
Labels: documentation, accessibility

#79 Adds post fetch to sleep data
  src/Activity.js
  src/Sleep.js
  src/apiCalls.js
  src/scripts.js
Labels: documentation, enhancement

#80 change unordered list to p as well as add the activity fetch
  dist/index.html
  src/apiCalls.js
  src/scripts.js
Labels: feature

#81 Adds fetch GET to hydration
  src/Sleep.js
  src/apiCalls.js
  src/scripts.js
Labels: bug, documentation

#83 Adds a revamp of HTML and new styles as well as two methods
  dist/index.html
  src/Activity.js
  src/css/styles.css
  test/Activity-test.js
Labels: bug, enhancement

#84 add helper functions and add get miles from steps
  src/Activity.js
  test/Activity-test.js
Labels: documentation

#86 add activity methods for returning users averages
  src/Activity.js
  src/Sleep.js
  test/Activity-test.js
Labels: documentation, help wanted, question

#85 add record function to activity and edit the activity form
  dist/index.html
  src/Activity.js
  src/css/styles.css
  test/Activity-test.js
Labels: bug

#87 Finish all time stairs method
  src/Activity.js
  test/Activity-test.js
Labels: enhancement

#88 Add an error handlging function to API
  src/apiCalls.js
Labels: enhancement

#89 Adds the rest of the step methods
  src/Activity.js
  test/Activity-test.js
Labels: documentation, enhancement

#90 Adds html changes
  dist/index.html
  src/css/styles.css
Labels: enhancement

#91 add edits to html
  dist/index.html
  src/apiCalls.js
  src/css/styles.css
  src/images/blue-clouds.png
  src/images/pink-cloud.png
  src/scripts.js
Labels: enhancement

#92 add displayActivityData
  dist/index.html
  src/scripts.js
Labels: enhancement

#94 Fix syntax error in HTML
  dist/index.html
Labels: enhancement
