Repository Leoy23/down-with-the-fitness, pull requests merged in 2022-08, with the labels that each got.

#37 Add findUSerDataID and userDailyOunces to our Hydration.js file
  src/Hydration.js
  test/Hydration-test.js
  test/UserRepository-test.js
Labels: bug

#38 Sleep methods
  src/Sleep.js
  src/data/sleepData.js
  src/scripts.js
  test/Sleep-test.js
Labels: bug

#41 Adds methods to hydration
  src/Hydration.js
  src/scripts.js
  test/Hydration-test.js
Labels: bug, enhancement

#40 Add icons to html and css
  dist/index.html
  src/css/styles.css
  src/scripts.js
Labels: enhancement
